export const MOCK_DATA_HOC_LAI = [
    {
        "id": 5792,
        "studentCode": "20210110P",
        "fullName": "Lê Tuấn Anh",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "Anh.LT210110P@sis.hust.edu.vn",
        "citizen": "030202010264",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-4",
        "termCode": "IT3100",
        "subjectCode": "IT3100",
        "subjectName": "Lập trình hướng đối tượng",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5791,
        "studentCode": "20210112P",
        "fullName": "Đỗ Tiến Tây Anh",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "Anh.DTT210112P@sis.hust.edu.vn",
        "citizen": "030103011375",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-4",
        "termCode": "IT3100",
        "subjectCode": "IT3100",
        "subjectName": "Lập trình hướng đối tượng",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5769,
        "studentCode": "20210112P",
        "fullName": "Đỗ Tiến Tây Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.DTT210112P@sis.hust.edu.vn",
        "citizen": "030103011375",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "IT3100",
        "subjectCode": "IT3100",
        "subjectName": "Lập trình hướng đối tượng",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5768,
        "studentCode": "20210110P",
        "fullName": "Lê Tuấn Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.LT210110P@sis.hust.edu.vn",
        "citizen": "030202010264",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "IT3090",
        "subjectCode": "IT3090",
        "subjectName": "CƠ SỞ DỮ LIỆU",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5767,
        "studentCode": "20210108P",
        "fullName": "Nguyễn Linh Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.NL210108P@sis.hust.edu.vn",
        "citizen": "001203023487",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "IT3080",
        "subjectCode": "IT3080",
        "subjectName": "Mạng máy tính",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5766,
        "studentCode": "20210107P",
        "fullName": "Nguyễn Quang Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.NQ210107P@sis.hust.edu.vn",
        "citizen": "001203001950",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "IT3070",
        "subjectCode": "IT3070",
        "subjectName": "Nguyên lý hệ điều hành",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5761,
        "studentCode": "20210105P",
        "fullName": "Nguyễn Khánh An",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "An.NK210105P@sis.hust.edu.vn",
        "citizen": "001203019409",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "IT3011",
        "subjectCode": "IT3011",
        "subjectName": "Cấu trúc dữ liệu và thuật toán",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5746,
        "studentCode": "20249015P",
        "fullName": "Nguyễn Bá Quảng",
        "gender": "MALE",
        "status": "REGISTERED",
        "email": "hoangtm.22810340407@epu.edu.vn",
        "citizen": "02134569877",
        "degreeType": "BACHELOR",
        "className": "Tin học kinh tế",
        "courseName": "Khóa 66",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Trường Cao đẳng Dầu khí",
        "sessionCode": "20261-A-5",
        "termCode": "PE2261",
        "subjectCode": "PE2261",
        "subjectName": "Karatedo",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5745,
        "studentCode": "20249015P",
        "fullName": "Nguyễn Bá Quảng",
        "gender": "MALE",
        "status": "REGISTERED",
        "email": "hoangtm.22810340407@epu.edu.vn",
        "citizen": "02134569877",
        "degreeType": "BACHELOR",
        "className": "Tin học kinh tế",
        "courseName": "Khóa 66",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Trường Cao đẳng Dầu khí",
        "sessionCode": "20261-A-5",
        "termCode": "ET4924",
        "subjectCode": "ET4924",
        "subjectName": "Đồ án nghiên cứu Cử nhân",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5744,
        "studentCode": "20249015P",
        "fullName": "Nguyễn Bá Quảng",
        "gender": "MALE",
        "status": "NOT_REGISTERED",
        "email": "hoangtm.22810340407@epu.edu.vn",
        "citizen": "02134569877",
        "degreeType": "BACHELOR",
        "className": "Tin học kinh tế",
        "courseName": "Khóa 66",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Trường Cao đẳng Dầu khí",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5743,
        "studentCode": "20249015P",
        "fullName": "Nguyễn Bá Quảng",
        "gender": "MALE",
        "status": "REGISTERED",
        "email": "hoangtm.22810340407@epu.edu.vn",
        "citizen": "02134569877",
        "degreeType": "BACHELOR",
        "className": "Tin học kinh tế",
        "courseName": "Khóa 66",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Trường Cao đẳng Dầu khí",
        "sessionCode": "20261-A-5",
        "termCode": "ET4596",
        "subjectCode": "ET4596",
        "subjectName": "Tin sinh học",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5742,
        "studentCode": "20249015P",
        "fullName": "Nguyễn Bá Quảng",
        "gender": "MALE",
        "status": "NOT_REGISTERED",
        "email": "hoangtm.22810340407@epu.edu.vn",
        "citizen": "02134569877",
        "degreeType": "BACHELOR",
        "className": "Tin học kinh tế",
        "courseName": "Khóa 66",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Trường Cao đẳng Dầu khí",
        "sessionCode": "20261-A-5",
        "termCode": "DD",
        "subjectCode": "DD",
        "subjectName": "Docker & Deploy",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5741,
        "studentCode": "20249015P",
        "fullName": "Nguyễn Bá Quảng",
        "gender": "MALE",
        "status": "NOT_REGISTERED",
        "email": "hoangtm.22810340407@epu.edu.vn",
        "citizen": "02134569877",
        "degreeType": "BACHELOR",
        "className": "Tin học kinh tế",
        "courseName": "Khóa 66",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Trường Cao đẳng Dầu khí",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5740,
        "studentCode": "20230004P",
        "fullName": "Nguyễn Phước Dũng",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20230004P@gmail.com",
        "citizen": "052099005578",
        "degreeType": "BACHELOR",
        "className": "LT-PM-KTYS01-K68",
        "courseName": "Khóa 68",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Trường Cao đẳng Y tế và Thiết bị Việt Đức",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5739,
        "studentCode": "20230004P",
        "fullName": "Nguyễn Phước Dũng",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20230004P@gmail.com",
        "citizen": "052099005578",
        "degreeType": "BACHELOR",
        "className": "LT-PM-KTYS01-K68",
        "courseName": "Khóa 68",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Trường Cao đẳng Y tế và Thiết bị Việt Đức",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5738,
        "studentCode": "20230002P",
        "fullName": "Trần Hữu Thạch Anh",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20230002P@gmail.com",
        "citizen": "022201006221",
        "degreeType": "BACHELOR",
        "className": "LT-PM-KTYS01-K68",
        "courseName": "Khóa 68",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Trường Cao đẳng Y tế và Thiết bị Việt Đức",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5737,
        "studentCode": "20230002P",
        "fullName": "Trần Hữu Thạch Anh",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20230002P@gmail.com",
        "citizen": "022201006221",
        "degreeType": "BACHELOR",
        "className": "LT-PM-KTYS01-K68",
        "courseName": "Khóa 68",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Trường Cao đẳng Y tế và Thiết bị Việt Đức",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5736,
        "studentCode": "20230001P",
        "fullName": "Đỗ Quang Anh",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20230001P@gmail.com",
        "citizen": "037201000932",
        "degreeType": "BACHELOR",
        "className": "LT-PM-KTYS01-K68",
        "courseName": "Khóa 68",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Trường Cao đẳng Y tế và Thiết bị Việt Đức",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5735,
        "studentCode": "20230001P",
        "fullName": "Đỗ Quang Anh",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20230001P@gmail.com",
        "citizen": "037201000932",
        "degreeType": "BACHELOR",
        "className": "LT-PM-KTYS01-K68",
        "courseName": "Khóa 68",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Trường Cao đẳng Y tế và Thiết bị Việt Đức",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5734,
        "studentCode": "20221154P",
        "fullName": "Lê Bá Toàn",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20221154P@gmail.com",
        "citizen": "001201013730",
        "degreeType": "BACHELOR",
        "className": "CQVLVH25.KTYS",
        "courseName": "Chính qui chuyển VLVH",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5733,
        "studentCode": "20221154P",
        "fullName": "Lê Bá Toàn",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20221154P@gmail.com",
        "citizen": "001201013730",
        "degreeType": "BACHELOR",
        "className": "CQVLVH25.KTYS",
        "courseName": "Chính qui chuyển VLVH",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5732,
        "studentCode": "20221142P",
        "fullName": "Bùi Minh Hoàng",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "hoangmih334+20221142P@gmail.com",
        "citizen": "001098008788",
        "degreeType": "BACHELOR",
        "className": "CQVLVH25.KTYS",
        "courseName": "Chính qui chuyển VLVH",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5731,
        "studentCode": "20221142P",
        "fullName": "Bùi Minh Hoàng",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "hoangmih334+20221142P@gmail.com",
        "citizen": "001098008788",
        "degreeType": "BACHELOR",
        "className": "CQVLVH25.KTYS",
        "courseName": "Chính qui chuyển VLVH",
        "majorName": "Kỹ thuật Y sinh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5720,
        "studentCode": "20210126P",
        "fullName": "Vũ Tiến Đạt",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Dat.VT210126P@sis.hust.edu.vn",
        "citizen": "30203006178",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5719,
        "studentCode": "20210126P",
        "fullName": "Vũ Tiến Đạt",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Dat.VT210126P@sis.hust.edu.vn",
        "citizen": "30203006178",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5718,
        "studentCode": "20210119P",
        "fullName": "Nguyễn Thị Thùy Dung",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Dung.NTT210119P@sis.hust.edu.vn",
        "citizen": "038303021247",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5717,
        "studentCode": "20210119P",
        "fullName": "Nguyễn Thị Thùy Dung",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Dung.NTT210119P@sis.hust.edu.vn",
        "citizen": "038303021247",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5716,
        "studentCode": "20210118P",
        "fullName": "Lê Văn Chiến",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Chien.LV210118P@sis.hust.edu.vn",
        "citizen": "030203010455",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5715,
        "studentCode": "20210118P",
        "fullName": "Lê Văn Chiến",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Chien.LV210118P@sis.hust.edu.vn",
        "citizen": "030203010455",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5714,
        "studentCode": "20210117P",
        "fullName": "Bùi Minh Chiến",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Chien.BM210117P@sis.hust.edu.vn",
        "citizen": "031202003181",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5713,
        "studentCode": "20210117P",
        "fullName": "Bùi Minh Chiến",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Chien.BM210117P@sis.hust.edu.vn",
        "citizen": "031202003181",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5712,
        "studentCode": "20210115P",
        "fullName": "Nguyễn Hữu Cường",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Cuong.NH210115P@sis.hust.edu.vn",
        "citizen": "027203008242",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5711,
        "studentCode": "20210115P",
        "fullName": "Nguyễn Hữu Cường",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Cuong.NH210115P@sis.hust.edu.vn",
        "citizen": "027203008242",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5710,
        "studentCode": "20210112P",
        "fullName": "Đỗ Tiến Tây Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.DTT210112P@sis.hust.edu.vn",
        "citizen": "030103011375",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5709,
        "studentCode": "20210112P",
        "fullName": "Đỗ Tiến Tây Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.DTT210112P@sis.hust.edu.vn",
        "citizen": "030103011375",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5708,
        "studentCode": "20210110P",
        "fullName": "Lê Tuấn Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.LT210110P@sis.hust.edu.vn",
        "citizen": "030202010264",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5707,
        "studentCode": "20210110P",
        "fullName": "Lê Tuấn Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.LT210110P@sis.hust.edu.vn",
        "citizen": "030202010264",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5702,
        "studentCode": "20210105P",
        "fullName": "Nguyễn Khánh An",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "An.NK210105P@sis.hust.edu.vn",
        "citizen": "001203019409",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5701,
        "studentCode": "20210105P",
        "fullName": "Nguyễn Khánh An",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "An.NK210105P@sis.hust.edu.vn",
        "citizen": "001203019409",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5705,
        "studentCode": "20210108P",
        "fullName": "Nguyễn Linh Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.NL210108P@sis.hust.edu.vn",
        "citizen": "001203023487",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5706,
        "studentCode": "20210108P",
        "fullName": "Nguyễn Linh Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.NL210108P@sis.hust.edu.vn",
        "citizen": "001203023487",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5703,
        "studentCode": "20210107P",
        "fullName": "Nguyễn Quang Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.NQ210107P@sis.hust.edu.vn",
        "citizen": "001203001950",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5704,
        "studentCode": "20210107P",
        "fullName": "Nguyễn Quang Anh",
        "gender": "OTHER",
        "status": "REGISTERED",
        "email": "Anh.NQ210107P@sis.hust.edu.vn",
        "citizen": "001203001950",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-5",
        "termCode": "CH2021",
        "subjectCode": "CH2021",
        "subjectName": "Đổi mới sáng tạo và khởi nghiệp",
        "failedScore": null,
        "isRegistered": true
    },
    {
        "id": 5685,
        "studentCode": "20175538",
        "fullName": "Mai Thị Thảo Nhi",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "nhi.mtt175538@sis.hust.edu.vn",
        "citizen": "031204056789",
        "degreeType": "BACHELOR",
        "className": "Khóa 62 - Tất cả các ngành học - Chính quy",
        "courseName": "Khóa 62",
        "majorName": "Tất cả các ngành học",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Chưa xác định",
        "sessionCode": "20261-A-4",
        "termCode": "PE2261",
        "subjectCode": "PE2261",
        "subjectName": "Karatedo",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5684,
        "studentCode": "20175538",
        "fullName": "Mai Thị Thảo Nhi",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "nhi.mtt175538@sis.hust.edu.vn",
        "citizen": "031204056789",
        "degreeType": "BACHELOR",
        "className": "Khóa 62 - Tất cả các ngành học - Chính quy",
        "courseName": "Khóa 62",
        "majorName": "Tất cả các ngành học",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Chưa xác định",
        "sessionCode": "20261-A-4",
        "termCode": "ET4596",
        "subjectCode": "ET4596",
        "subjectName": "Tin sinh học",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5683,
        "studentCode": "20175538",
        "fullName": "Mai Thị Thảo Nhi",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "nhi.mtt175538@sis.hust.edu.vn",
        "citizen": "031204056789",
        "degreeType": "BACHELOR",
        "className": "Khóa 62 - Tất cả các ngành học - Chính quy",
        "courseName": "Khóa 62",
        "majorName": "Tất cả các ngành học",
        "trainingMethodName": "Chính quy",
        "trainingUnitName": "Chưa xác định",
        "sessionCode": "20261-A-4",
        "termCode": "CSHARP",
        "subjectCode": "CSHARP",
        "subjectName": "Lập trình C#",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5682,
        "studentCode": "20262847",
        "fullName": "Nguyễn Minh Đức",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "ducnmx9@gmail.com",
        "citizen": "013395769",
        "degreeType": "BACHELOR",
        "className": "Khóa 71 - Kỹ thuật Điều khiển và Tự động hóa - Vừa làm vừa học",
        "courseName": "Khóa 71",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Chưa xác định",
        "sessionCode": "20261-A-4",
        "termCode": "EE3482",
        "subjectCode": "EE3482",
        "subjectName": "Vật liệu điện",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5681,
        "studentCode": "20262847",
        "fullName": "Nguyễn Minh Đức",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "ducnmx9@gmail.com",
        "citizen": "013395769",
        "degreeType": "BACHELOR",
        "className": "Khóa 71 - Kỹ thuật Điều khiển và Tự động hóa - Vừa làm vừa học",
        "courseName": "Khóa 71",
        "majorName": "Kỹ thuật Điều khiển và Tự động hóa",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Chưa xác định",
        "sessionCode": "20261-A-4",
        "termCode": "EE2012",
        "subjectCode": "EE2012",
        "subjectName": "Kỹ thuật điện",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5666,
        "studentCode": "20259058P",
        "fullName": "Phạm Minh Quốc Quân",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "Phamq1225@gmail.com",
        "citizen": "014205000336",
        "degreeType": "BACHELOR",
        "className": "CQVLVH25.ĐTVT",
        "courseName": "Chính qui chuyển VLVH",
        "majorName": "Kỹ thuật Điện tử - Viễn thông",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-4",
        "termCode": "MHP02",
        "subjectCode": "MHP02",
        "subjectName": "Pháp luật đại cương Q",
        "failedScore": null,
        "isRegistered": false
    },
    {
        "id": 5665,
        "studentCode": "20259058P",
        "fullName": "Phạm Minh Quốc Quân",
        "gender": "OTHER",
        "status": "NOT_REGISTERED",
        "email": "Phamq1225@gmail.com",
        "citizen": "014205000336",
        "degreeType": "BACHELOR",
        "className": "CQVLVH25.ĐTVT",
        "courseName": "Chính qui chuyển VLVH",
        "majorName": "Kỹ thuật Điện tử - Viễn thông",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội",
        "sessionCode": "20261-A-4",
        "termCode": "MHP01",
        "subjectCode": "MHP01",
        "subjectName": "Pháp luật đại cương H",
        "failedScore": null,
        "isRegistered": false
    }
];