export const MOCK_DATA_GIANG_VIEN = [
    {
        "id": 681,
        "code": "TTBY01",
        "fullName": "Trần Bảo Yến",
        "phone": "0856146936",
        "email": "baoien121124@gmail.com",
        "birthday": null,
        "gender": "FEMALE",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 661,
        "code": "GV_271204",
        "fullName": "Trần Mạnh Dũng",
        "phone": "0327699521",
        "email": "dungtm@gmail.com",
        "birthday": "29/12/2004 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "GV_271204",
        "bankNumber": "1024203297",
        "bankName": "Vietcombank",
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 641,
        "code": "GV_260520_002",
        "fullName": "Trần Mạnh Hải",
        "phone": "0988096338",
        "email": "haitm@gmail.com",
        "birthday": "28/12/2004 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "GV_260520_002",
        "bankNumber": null,
        "bankName": "BIDV",
        "taxCode": "8075678901",
        "workUnit": null,
        "semester": null
    },
    {
        "id": 621,
        "code": "GV_260520_001",
        "fullName": "Trần Ngọc Anh ",
        "phone": "0965336221",
        "email": "test06@onebs.vn",
        "birthday": "01/10/2000 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "GV_260520_001",
        "bankNumber": null,
        "bankName": "SHB",
        "taxCode": "4502320054",
        "workUnit": null,
        "semester": null
    },
    {
        "id": 601,
        "code": "002.014.00046",
        "fullName": "Lưu Thị Oanh",
        "phone": null,
        "email": "oanh.luuthi@hust.edu.vn",
        "birthday": "03/05/1961 00:00:00",
        "gender": "FEMALE",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "002.014.00046",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 583,
        "code": "GV002",
        "fullName": "Nguyễn Ngọc Mai",
        "phone": "0911223344",
        "email": "mai.nguyen@gmail.com",
        "birthday": null,
        "gender": "FEMALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "GV002 ",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 582,
        "code": "GV_260512_003",
        "fullName": "Nguyễn Hoàng Yến",
        "phone": "0986552004",
        "email": "gvtest03@onebs.vn",
        "birthday": "03/02/1996 00:00:00",
        "gender": "FEMALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "GV_260512_003",
        "bankNumber": null,
        "bankName": "SHB",
        "taxCode": "4023653985",
        "workUnit": null,
        "semester": null
    },
    {
        "id": 581,
        "code": "GV_260512_002",
        "fullName": "Trần Ngọc Anh Thư",
        "phone": "0986552337",
        "email": "gvtest02@onebs.vn",
        "birthday": "01/07/1990 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "GV_260512_002",
        "bankNumber": null,
        "bankName": "SHB",
        "taxCode": "7634679467",
        "workUnit": {
            "id": 220,
            "code": "11.39",
            "name": "Phòng Tuyển sinh",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 561,
        "code": "GV001",
        "fullName": "Nguyễn Văn An",
        "phone": null,
        "email": "an.nguyen@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 541,
        "code": "TEST_999",
        "fullName": "Test 99998",
        "phone": "0986009338",
        "email": "test01999@onebs.vn",
        "birthday": "16/04/2000 00:00:00",
        "gender": "OTHER",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "string",
        "bankNumber": "940737785",
        "bankName": "BIDV",
        "taxCode": "9878675",
        "workUnit": {
            "id": 217,
            "code": "11.33",
            "name": "Phòng Thanh tra Pháp chế",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 521,
        "code": "GV_TEST_01",
        "fullName": "GV TEST 01",
        "phone": "0336859886",
        "email": "gv_test01@onebs.vn",
        "birthday": "15/04/2020 02:36:40",
        "gender": "OTHER",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "string",
        "bankNumber": "0893733702",
        "bankName": "BIDV",
        "taxCode": "293972984",
        "workUnit": {
            "id": 247,
            "code": "07.01\t",
            "name": "VP Viện Điện tủ-Viễn thông\t",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 502,
        "code": "TEST_01",
        "fullName": "Test 65",
        "phone": "0900887222",
        "email": "test069@onebs.vn",
        "birthday": "14/04/2000 00:00:00",
        "gender": "OTHER",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": null,
        "bankNumber": "940531307",
        "bankName": "BIDV",
        "taxCode": "3542999",
        "workUnit": null,
        "semester": null
    },
    {
        "id": 501,
        "code": "TEST",
        "fullName": "Trần mạnh dũng",
        "phone": "0327699528",
        "email": "123@123.com",
        "birthday": "27/12/2004 00:00:00",
        "gender": "FEMALE",
        "status": "INACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1024203297",
        "bankName": "TEST",
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 481,
        "code": "BCH_001",
        "fullName": "Bùi Chí Hiếu",
        "phone": "0325978045",
        "email": "buigm2002@gmail.com",
        "birthday": "08/05/2002 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "MDT_001",
        "bankNumber": "2120972547",
        "bankName": "BIDV",
        "taxCode": "MST_001",
        "workUnit": {
            "id": 208,
            "code": "11.20",
            "name": "Phòng Quản lý chất lượng",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 451,
        "code": "GV199",
        "fullName": "GV23",
        "phone": null,
        "email": "anhtus@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "GV199",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 224,
            "code": "12.03",
            "name": "Tự động hoá XNCN",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 450,
        "code": "GV198",
        "fullName": "GV22",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "GV198",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 222,
            "code": "12.01",
            "name": "VP Viện Điện",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 449,
        "code": "GV197",
        "fullName": "GV21",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "GV197",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 223,
            "code": "12.02",
            "name": "Hệ thống điện",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 448,
        "code": "GV196",
        "fullName": "GV20",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "GV196",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 224,
            "code": "12.03",
            "name": "Tự động hoá XNCN",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 447,
        "code": "GV195",
        "fullName": "GV19",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "GV195",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 222,
            "code": "12.01",
            "name": "VP Viện Điện",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 421,
        "code": "ASF1",
        "fullName": "asd1",
        "phone": null,
        "email": "a1es@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "asd1",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 210,
            "code": "11.22",
            "name": "Trung Tâm Ký túc xá",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 405,
        "code": "002.004.00565",
        "fullName": "Vũ Song Tùng",
        "phone": null,
        "email": "tung.a@hust.edu.vn",
        "birthday": null,
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1220435424",
        "bankName": null,
        "taxCode": "2147483647",
        "workUnit": {
            "id": 220,
            "code": "11.39",
            "name": "Phòng Tuyển sinh",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 404,
        "code": "002.004.00006",
        "fullName": "Dương Trọng Lượng",
        "phone": null,
        "email": "luong.a@hust.edu.vn",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1220284343",
        "bankName": null,
        "taxCode": "2147483647",
        "workUnit": {
            "id": 221,
            "code": "11.44",
            "name": "Thư viện Tạ Quang Bửu",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 403,
        "code": "002.004.00530",
        "fullName": "Phương Xuân Quang",
        "phone": null,
        "email": "quang.pxuan@hust.edu.vn",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1220285133",
        "bankName": null,
        "taxCode": "2147483647",
        "workUnit": {
            "id": 223,
            "code": "12.02",
            "name": "Hệ thống điện",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 402,
        "code": "002.004.00101",
        "fullName": "Nguyễn Thị Kim Thoa",
        "phone": null,
        "email": "anhtumc9ass@gmail.com",
        "birthday": null,
        "gender": "FEMALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1220305402",
        "bankName": null,
        "taxCode": "2147483647",
        "workUnit": {
            "id": 214,
            "code": "11.28",
            "name": "Phòng Phát triển dự án và đầu tư",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 401,
        "code": "002.041.00013",
        "fullName": "Nguyễn Việt Dũng",
        "phone": null,
        "email": "dung.nguyenviet@haust.edu.vn",
        "birthday": null,
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1220289409",
        "bankName": null,
        "taxCode": "2147483647",
        "workUnit": {
            "id": 209,
            "code": "11.21",
            "name": "Phòng khám đa khoa BK",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 400,
        "code": "002.004.00057",
        "fullName": "Đào Lê Thu Thảo",
        "phone": null,
        "email": "thao.daolethu@huast.edu.vn",
        "birthday": null,
        "gender": "OTHER",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": "1220291909",
        "bankName": null,
        "taxCode": "2147483647",
        "workUnit": {
            "id": 223,
            "code": "12.02",
            "name": "Hệ thống điện",
            "address": "Trường Điện - Điện tử\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 399,
        "code": "GV63",
        "fullName": "Kiên",
        "phone": null,
        "email": "a@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 210,
            "code": "11.22",
            "name": "Trung Tâm Ký túc xá",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 397,
        "code": "GV61",
        "fullName": "Mỹ",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 396,
        "code": "GV60",
        "fullName": "Chi",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 391,
        "code": "GV59",
        "fullName": "Oanh1",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 389,
        "code": "GV562",
        "fullName": "Hiệp",
        "phone": "0785438978",
        "email": "h@gmail.com",
        "birthday": "20/08/1997 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": {
            "id": 214,
            "code": "11.28",
            "name": "Phòng Phát triển dự án và đầu tư",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 388,
        "code": "GV561",
        "fullName": "Mỹ",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 387,
        "code": "GV560",
        "fullName": "Chi",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 361,
        "code": "gv0909",
        "fullName": "abc",
        "phone": null,
        "email": "aaas@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "1234",
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 341,
        "code": "aaa",
        "fullName": "aa",
        "phone": null,
        "email": null,
        "birthday": null,
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": null,
        "workUnit": null,
        "semester": null
    },
    {
        "id": 321,
        "code": "123",
        "fullName": "TKieen",
        "phone": "0917199888",
        "email": "anhkienit3011@gmail.com",
        "birthday": "12/05/1988 00:00:00",
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "24134",
        "bankNumber": "1231241234213",
        "bankName": "VP",
        "taxCode": "12412354235",
        "workUnit": {
            "id": 210,
            "code": "11.22",
            "name": "Trung Tâm Ký túc xá",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 301,
        "code": "M26",
        "fullName": "Oanh",
        "phone": null,
        "email": "anh@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": null,
        "bankNumber": null,
        "bankName": null,
        "taxCode": "1242532",
        "workUnit": {
            "id": 212,
            "code": "11.24",
            "name": "Khoa Giáo dục Quốc phòng",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 290,
        "code": "GV_09",
        "fullName": "nguyễn văn test",
        "phone": "0912456356",
        "email": "test@gmail.com",
        "birthday": null,
        "gender": null,
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "DT_09",
        "bankNumber": "435435",
        "bankName": "viettinbank",
        "taxCode": "4543",
        "workUnit": {
            "id": 214,
            "code": "11.28",
            "name": "Phòng Phát triển dự án và đầu tư",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 289,
        "code": "GV_08",
        "fullName": "Đỗ Hồng Kiên",
        "phone": "0912456355",
        "email": "nguyenminhanhchieu@gmail.com",
        "birthday": null,
        "gender": "MALE",
        "status": "ACTIVE",
        "lecturerStatus": "VISITING",
        "officerCode": "DT_08",
        "bankNumber": "0000567435435",
        "bankName": "Viettinbank",
        "taxCode": "4543",
        "workUnit": {
            "id": 210,
            "code": "11.22",
            "name": "Trung Tâm Ký túc xá",
            "address": "Hà Nội\t",
            "status": "ACTIVE"
        },
        "semester": null
    },
    {
        "id": 288,
        "code": "GV_07",
        "fullName": "Phương Oanh",
        "phone": "0965344554",
        "email": "linhlananhh@gmail.com",
        "birthday": "04/02/1970 00:00:00",
        "gender": "FEMALE",
        "status": "ACTIVE",
        "lecturerStatus": "FULL_TIME",
        "officerCode": "DT_07",
        "bankNumber": "0000465778899",
        "bankName": "vietcombank",
        "taxCode": "455461",
        "workUnit": {
            "id": 212,
            "code": "11.24",
            "name": "Khoa Giáo dục Quốc phòng",
            "address": null,
            "status": "ACTIVE"
        },
        "semester": null
    }
];