export const MOCK_DATA_SINH_VIEN = [
    {
        "id": 5741,
        "code": "20210452P",
        "fullName": "Phan Thị Phương",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Phuong.PT210452P@sis.hust.edu.vn",
        "citizen": "030303010695",
        "degreeType": "BACHELOR",
        "className": "DH-BK-KT01-K67",
        "courseName": "Khóa 67",
        "majorName": "Kế toán",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5740,
        "code": "20210344P",
        "fullName": "Vũ Phương Linh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Linh.VP210344P@sis.hust.edu.vn",
        "citizen": "038303010963",
        "degreeType": "BACHELOR",
        "className": "DH-BK-QTKD2.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Quản trị kinh doanh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5739,
        "code": "20210377P",
        "fullName": "Trịnh Thanh Tâm",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Tam.TT210377P@sis.hust.edu.vn",
        "citizen": "080303000606",
        "degreeType": "BACHELOR",
        "className": "DH-BK-QTKD2.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Quản trị kinh doanh",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5738,
        "code": "20210105P",
        "fullName": "Nguyễn Khánh An",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "An.NK210105P@sis.hust.edu.vn",
        "citizen": "001203019409",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5737,
        "code": "20210108P",
        "fullName": "Nguyễn Linh Anh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Anh.NL210108P@sis.hust.edu.vn",
        "citizen": "001203023487",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5736,
        "code": "20210110P",
        "fullName": "Lê Tuấn Anh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Anh.LT210110P@sis.hust.edu.vn",
        "citizen": "030202010264",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5735,
        "code": "20210112P",
        "fullName": "Đỗ Tiến Tây Anh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Anh.DTT210112P@sis.hust.edu.vn",
        "citizen": "030103011375",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5734,
        "code": "20210107P",
        "fullName": "Nguyễn Quang Anh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Anh.NQ210107P@sis.hust.edu.vn",
        "citizen": "001203001950",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5733,
        "code": "20210697P",
        "fullName": "Phạm Tuấn Anh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Anh.PT210697P@sis.hust.edu.vn",
        "citizen": "122413753",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5732,
        "code": "20210115P",
        "fullName": "Nguyễn Hữu Cường",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Cuong.NH210115P@sis.hust.edu.vn",
        "citizen": "027203008242",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5731,
        "code": "20210117P",
        "fullName": "Bùi Minh Chiến",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Chien.BM210117P@sis.hust.edu.vn",
        "citizen": "031202003181",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5730,
        "code": "20210118P",
        "fullName": "Lê Văn Chiến",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Chien.LV210118P@sis.hust.edu.vn",
        "citizen": "030203010455",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5729,
        "code": "20210119P",
        "fullName": "Nguyễn Thị Thùy Dung",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Dung.NTT210119P@sis.hust.edu.vn",
        "citizen": "038303021247",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5728,
        "code": "20210700P",
        "fullName": "Phạm Công Dũng",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Dung.PC210700P@sis.hust.edu.vn",
        "citizen": "030203002546",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5727,
        "code": "20210127P",
        "fullName": "Đỗ Tiến Đạt",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Dat.DT210127P@sis.hust.edu.vn",
        "citizen": "030203003419",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5726,
        "code": "20210126P",
        "fullName": "Vũ Tiến Đạt",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Dat.VT210126P@sis.hust.edu.vn",
        "citizen": "30203006178",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5725,
        "code": "20210128P",
        "fullName": "Nguyễn Anh Đức",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Duc.NA210128P@sis.hust.edu.vn",
        "citizen": "031203003926",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5724,
        "code": "20210134P",
        "fullName": "Nguyễn Văn Đức",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Duc.NV210134P@sis.hust.edu.vn",
        "citizen": "030203009992",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5723,
        "code": "20210132P",
        "fullName": "Nguyễn Mạnh Đức",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Duc.NM210132P@sis.hust.edu.vn",
        "citizen": "031203005702",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5722,
        "code": "20210224P",
        "fullName": "Nguyễn Minh Đức",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Duc.NM210224P@sis.hust.edu.vn",
        "citizen": "001203049369",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5721,
        "code": "20210136P",
        "fullName": "Ngô Thị Hương Giang",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Giang.NTH210136P@sis.hust.edu.vn",
        "citizen": "030303006595",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5720,
        "code": "20210143P",
        "fullName": "Hoàng Trung Hiếu",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hieu.HT210143P@sis.hust.edu.vn",
        "citizen": "025203013103",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5719,
        "code": "20210144P",
        "fullName": "Đỗ Ngọc Hiếu",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hieu.DN210144P@sis.hust.edu.vn",
        "citizen": "001203007390",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5718,
        "code": "20210145P",
        "fullName": "Ngô Trung Hiếu",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hieu.NT210145P@sis.hust.edu.vn",
        "citizen": "001203022858",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5717,
        "code": "20210147P",
        "fullName": "Nguyễn Xuân Hòa",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hoa.NX210147P@sis.hust.edu.vn",
        "citizen": "038203021727",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5716,
        "code": "20210149P",
        "fullName": "Nguyễn Xuân Hoàng",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hoang.NX210149P@sis.hust.edu.vn",
        "citizen": "017033632",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5715,
        "code": "20210150P",
        "fullName": "Nguyễn Huy Hoằng",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hoang.NH210150P@sis.hust.edu.vn",
        "citizen": "031203006383",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5714,
        "code": "20210227P",
        "fullName": "Phạm Thanh Hùng",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Hung.PT210227P@sis.hust.edu.vn",
        "citizen": "001203028632",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5713,
        "code": "20210154P",
        "fullName": "Phạm Thành Huy",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Huy.PT210154P@sis.hust.edu.vn",
        "citizen": "001203004954",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5712,
        "code": "20210157P",
        "fullName": "Nguyễn Đăng Huy",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Huy.ND210157P@sis.hust.edu.vn",
        "citizen": "001203001728",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5711,
        "code": "20210158P",
        "fullName": "Lê Thu Huyền",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Huyen.LT210158P@sis.hust.edu.vn",
        "citizen": "036303005098",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5710,
        "code": "20210159P",
        "fullName": "Nguyễn Văn Huynh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Huynh.NV210159P@sis.hust.edu.vn",
        "citizen": "030203006675",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5709,
        "code": "20210162P",
        "fullName": "Nguyễn Văn Khương",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Khuong.NV210162P@sis.hust.edu.vn",
        "citizen": "030203003430",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5708,
        "code": "20210163P",
        "fullName": "Nguyễn Thị Thanh Lâm",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Lam.NTT210163P@sis.hust.edu.vn",
        "citizen": "031303006153",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5707,
        "code": "20210230P",
        "fullName": "Lê Phúc Lâm",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Lam.LP210230P@sis.hust.edu.vn",
        "citizen": "001203008166",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5706,
        "code": "20210164P",
        "fullName": "Đậu Khánh Linh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Linh.DK210164P@sis.hust.edu.vn",
        "citizen": "031303003144",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5705,
        "code": "20210168P",
        "fullName": "Nguyễn Kim Long",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Long.NK210168P@sis.hust.edu.vn",
        "citizen": "034203008611",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5704,
        "code": "20210170P",
        "fullName": "Phạm Đức Mạnh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Manh.PD210170P@sis.hust.edu.vn",
        "citizen": "001203047186",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5703,
        "code": "20210171P",
        "fullName": "Trần Xuân Mạnh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Manh.TX210171P@sis.hust.edu.vn",
        "citizen": "036203004139",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5702,
        "code": "20210172P",
        "fullName": "Nguyễn Viết Minh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Minh.NV210172P@sis.hust.edu.vn",
        "citizen": "001203025994",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5701,
        "code": "20210174P",
        "fullName": "Đoàn Đức Minh",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Minh.DD210174P@sis.hust.edu.vn",
        "citizen": "001203036303",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5700,
        "code": "20210176P",
        "fullName": "Nguyễn Lê Hoài Nam",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Nam.NLH210176P@sis.hust.edu.vn",
        "citizen": "031203001868",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5699,
        "code": "20210177P",
        "fullName": "Lê Văn Nam",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Nam.LV210177P@sis.hust.edu.vn",
        "citizen": "038203023517",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5698,
        "code": "20210179P",
        "fullName": "Mai Trung Nghĩa",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Nghia.MT210179P@sis.hust.edu.vn",
        "citizen": "031203007104",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5697,
        "code": "20210181P",
        "fullName": "Nguyễn Trung Nguyên",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Nguyen.NT210181P@sis.hust.edu.vn",
        "citizen": "037203005562",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5696,
        "code": "20210184P",
        "fullName": "Lê Thị Hồng Nhung",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Nhung.LTH210184P@sis.hust.edu.vn",
        "citizen": "036303005083",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5695,
        "code": "20210185P",
        "fullName": "Cấn Quang Phước",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Phuoc.CQ210185P@sis.hust.edu.vn",
        "citizen": "001203144480",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5694,
        "code": "20210187P",
        "fullName": "Đoàn Thị Thanh Phương",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Phuong.DTT210187P@sis.hust.edu.vn",
        "citizen": "034303008434",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5693,
        "code": "20210696P",
        "fullName": "Phạm Hồng Quân",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Quan.PH210696P@sis.hust.edu.vn",
        "citizen": "034203009013",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.2-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    },
    {
        "id": 5692,
        "code": "20210235P",
        "fullName": "Lê Văn Sơn",
        "gender": "OTHER",
        "status": "STUDYING",
        "email": "Son.LV210235P@sis.hust.edu.vn",
        "citizen": "038203019457",
        "degreeType": "BACHELOR",
        "className": "DH-BK-CNTT1.1-K66",
        "courseName": "Khóa 66",
        "majorName": "Công nghệ thông tin",
        "trainingMethodName": "Vừa làm vừa học",
        "trainingUnitName": "Đại học Bách khoa Hà Nội"
    }
];