export const MOCK_DATA_SINH_VIEN_HOC_LAI = 
{
  "pageIndex": 1,
  "pageSize": 50,
  "totalPages": 2,
  "totalRecords": 52,
  "data":
[
  {
    "id": 1201,
    "code": "20210001P",
    "fullName": "Nguyễn Thị Sơn",
    "email": "demo.hoclai.20210001p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1202,
    "code": "20210002P",
    "fullName": "Bùi Thị Thảo",
    "email": "demo.hoclai.20210002p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1203,
    "code": "20210003P",
    "fullName": "Phạm Thị Anh",
    "email": "demo.hoclai.20210003p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1204,
    "code": "20210004P",
    "fullName": "Đỗ Đình Hải",
    "email": "demo.hoclai.20210004p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1205,
    "code": "20210005P",
    "fullName": "Phạm Gia Trang",
    "email": "demo.hoclai.20210005p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1206,
    "code": "20210006P",
    "fullName": "Phạm Thị Việt",
    "email": "demo.hoclai.20210006p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1207,
    "code": "20210007P",
    "fullName": "Phú Văn Lộc",
    "email": "demo.hoclai.20210007p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1208,
    "code": "20210008P",
    "fullName": "Phạm Hữu Hiếu",
    "email": "demo.hoclai.20210008p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "CONFIRMED"
  },
  {
    "id": 1209,
    "code": "20210009P",
    "fullName": "Nguyễn Thanh Thu",
    "email": "demo.hoclai.20210009p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1210,
    "code": "20210010P",
    "fullName": "Nguyễn Thị Yến",
    "email": "demo.hoclai.20210010p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1211,
    "code": "20210011P",
    "fullName": "Đỗ Minh Ngọc",
    "email": "demo.hoclai.20210011p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "REJECTED"
  },
  {
    "id": 1212,
    "code": "20210012P",
    "fullName": "Hoàng Thị Cường",
    "email": "demo.hoclai.20210012p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1213,
    "code": "20210013P",
    "fullName": "Huỳnh Ngọc Hiếu",
    "email": "demo.hoclai.20210013p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1214,
    "code": "20210014P",
    "fullName": "Phạm Văn Long",
    "email": "demo.hoclai.20210014p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "CONFIRMED"
  },
  {
    "id": 1215,
    "code": "20210015P",
    "fullName": "Vũ Văn Hải",
    "email": "demo.hoclai.20210015p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1216,
    "code": "20210016P",
    "fullName": "Phú Văn Long",
    "email": "demo.hoclai.20210016p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1217,
    "code": "20210017P",
    "fullName": "Bùi Thị Yến",
    "email": "demo.hoclai.20210017p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1218,
    "code": "20210018P",
    "fullName": "Võ Thị Yến",
    "email": "demo.hoclai.20210018p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1219,
    "code": "20210019P",
    "fullName": "Hồ Thanh Sơn",
    "email": "demo.hoclai.20210019p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1220,
    "code": "20210020P",
    "fullName": "Đỗ Minh Trang",
    "email": "demo.hoclai.20210020p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "CONFIRMED"
  },
  {
    "id": 1221,
    "code": "20210021P",
    "fullName": "Vũ Văn Cường",
    "email": "demo.hoclai.20210021p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1222,
    "code": "20210022P",
    "fullName": "Phú Gia Hải",
    "email": "demo.hoclai.20210022p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1223,
    "code": "20210023P",
    "fullName": "Đỗ Thanh Tuấn",
    "email": "demo.hoclai.20210023p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1224,
    "code": "20210024P",
    "fullName": "Vũ Minh Hiếu",
    "email": "demo.hoclai.20210024p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1225,
    "code": "20210025P",
    "fullName": "Ngô Văn Hùng",
    "email": "demo.hoclai.20210025p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1226,
    "code": "20210026P",
    "fullName": "Nguyễn Thanh Thu",
    "email": "demo.hoclai.20210026p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1227,
    "code": "20210027P",
    "fullName": "Ngô Thị Thu",
    "email": "demo.hoclai.20210027p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1228,
    "code": "20210028P",
    "fullName": "Phú Văn Hải",
    "email": "demo.hoclai.20210028p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1229,
    "code": "20210029P",
    "fullName": "Đỗ Minh Long",
    "email": "demo.hoclai.20210029p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1230,
    "code": "20210030P",
    "fullName": "Đỗ Thị Long",
    "email": "demo.hoclai.20210030p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1231,
    "code": "20210031P",
    "fullName": "Hồ Quang Yến",
    "email": "demo.hoclai.20210031p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1232,
    "code": "20210032P",
    "fullName": "Phú Văn Lộc",
    "email": "demo.hoclai.20210032p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1233,
    "code": "20210033P",
    "fullName": "Vũ Văn Lộc",
    "email": "demo.hoclai.20210033p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1234,
    "code": "20210034P",
    "fullName": "Phạm Văn Bình",
    "email": "demo.hoclai.20210034p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1235,
    "code": "20210035P",
    "fullName": "Hồ Quang Trang",
    "email": "demo.hoclai.20210035p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1236,
    "code": "20210036P",
    "fullName": "Đỗ Minh Nam",
    "email": "demo.hoclai.20210036p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1237,
    "code": "20210037P",
    "fullName": "Hồ Minh Yến",
    "email": "demo.hoclai.20210037p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1238,
    "code": "20210038P",
    "fullName": "Nguyễn Văn Lộc",
    "email": "demo.hoclai.20210038p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1239,
    "code": "20210039P",
    "fullName": "Huỳnh Thanh Hương",
    "email": "demo.hoclai.20210039p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1240,
    "code": "20210040P",
    "fullName": "Huỳnh Thị Hiếu",
    "email": "demo.hoclai.20210040p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1241,
    "code": "20210041P",
    "fullName": "Vũ Minh Tuấn",
    "email": "demo.hoclai.20210041p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1242,
    "code": "20210042P",
    "fullName": "Nguyễn Minh Hương",
    "email": "demo.hoclai.20210042p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1243,
    "code": "20210043P",
    "fullName": "Đỗ Thanh Nga",
    "email": "demo.hoclai.20210043p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1244,
    "code": "20210044P",
    "fullName": "Phú Văn Lộc",
    "email": "demo.hoclai.20210044p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1245,
    "code": "20210045P",
    "fullName": "Phạm Văn Long",
    "email": "demo.hoclai.20210045p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1246,
    "code": "20210046P",
    "fullName": "Trần Thị Sơn",
    "email": "demo.hoclai.20210046p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3090", "name": "Cơ sở dữ liệu", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1247,
    "code": "20210047P",
    "fullName": "Hồ Gia Hải",
    "email": "demo.hoclai.20210047p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CK01-K66", "name": "DH-BK-CK01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Cơ khí"},
    "registerStudentTerms": [{"term": {"code": "IT3011", "name": "Cấu trúc dữ liệu và thuật toán", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1248,
    "code": "20210048P",
    "fullName": "Hồ Gia Hùng",
    "email": "demo.hoclai.20210048p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "IT3100", "name": "Lập trình hướng đối tượng", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1249,
    "code": "20210049P",
    "fullName": "Huỳnh Thanh Long",
    "email": "demo.hoclai.20210049p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1250,
    "code": "20210050P",
    "fullName": "Đỗ Minh Trang",
    "email": "demo.hoclai.20210050p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-EE01-K66", "name": "DH-BK-EE01-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Điện - Điện tử"},
    "registerStudentTerms": [{"term": {"code": "EE2011", "name": "Mạch điện 1", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1251,
    "code": "20210051P",
    "fullName": "Nguyễn Thanh Tuấn",
    "email": "demo.hoclai.20210051p@example.com",
    "totalFeeOfExam": 1000000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "CQVLVH25.KTYS", "name": "CQVLVH25.KTYS", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Kỹ thuật Y sinh"},
    "registerStudentTerms": [{"term": {"code": "ME2021", "name": "Sức bền vật liệu", "creditHours": 2.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  },
  {
    "id": 1252,
    "code": "20210052P",
    "fullName": "Vũ Thanh Cường",
    "email": "demo.hoclai.20210052p@example.com",
    "totalFeeOfExam": 1500000,
    "course": {"code": "K66", "name": "Khóa 66"},
    "clazz": {"code": "DH-BK-CNTT1.1-K66", "name": "DH-BK-CNTT1.1-K66", "trainingUnitName": "Đại học Bách khoa Hà Nội", "majorName": "Công nghệ thông tin"},
    "registerStudentTerms": [{"term": {"code": "IT3080", "name": "Mạng máy tính", "creditHours": 3.0}}],
    "registerStudentStatus": "AWAITING_CONFIRMATION"
  }
]
}